### ISSUE TITLE
update dgenerate

### ISSUE THREAD

**Issue by rahmirtrt** [Teriks/dgenerate#1] opened 2024-03-31 10:18 UTC
Can you update dgenerate for new models?

Spandrel now supports many more models.
https://github.com/chaiNNer-org/spandrel

degenerate is a very nice program. I use it constantly. 
Please continue your support.

**Comment by Teriks** [comment] 2024-04-03 04:44
I will take a look, this should be fairly simple to do

I do recall that I needed to possibly modify my usage of spandrel to not use tiling for certain models

I have become quite busy

**Comment by rahmirtrt** [comment] 2024-04-03 10:44
Thank you. I'm waiting for degenerate's new versions.

**Comment by Teriks** [comment] 2024-04-03 19:46
> Thank you. I'm waiting for degenerate's new versions(for new models).
> 
> whenever the (https://github.com/chaiNNer-org/spandrel/tree/main/libs/spandrel/spandrel) to (C:\Program Files\dgeneratet_internal\spandrel) folder is changed new models work. Can you develop dgenerate this way? Thus, there is no need to constantly update dgenerate(for new models).

Due to the way PyInstaller creates the environment under _internal, and the generated executables interactions with the environment when loading modules, the launcher will become unhappy about loading the module with version differences or renamed / now missing sources etc. Unfortunately it cannot be made to work that way for the windows installer, at least with PyInstaller.

It could be made to work that way if spandrel features could be loaded as an accessory module, with the user installing it manually into an environment of their own creation. For instance in the simple case, if you install dgenerate into it's own python environment instead of using the Windows installer, and then forcefully upgrade the spandrel package to 0.3.1, that would probably work (from what I am observing now) in the short term, as long as no major API changes actually occurred in spandrel. In the long term it has to be manually updated (in every case) to ensure that the dependency is still written against correctly with version changes, spandrel seems to be in fairly active development so something breaking with the API could happen frequently.

I will bump spandrel to latest and release a new installer once I ensure it is still working.

On Windows, the entire environment must be crafted carefully and frozen for this software to "just work" without any issues, and it just *barely* works as is, so I would imagine any tampering of dependencies in the _internal environment created by PyInstaller will cause it to tip into the "don't work" state very quickly. The windows installer is a convenience that trades off entirely the users ability to control the python environment / dependencies in favor of something that will just work when it is installed.

**Comment by rahmirtrt** [comment] 2024-04-04 17:28
I will test it and offer some suggestions.

**Comment by rahmirtrt** [comment] 2024-04-04 18:03
error 
image-process: error: [Errno 13] Permission denied: '.\\.lock'

I use this command.
dgenerate --sub-command image-process tmp2.jpg --output tmp2u.png -al 1 --processors "upscaler;model=models/4x_Real_SSDIR_DAT_GAN.pth"

**Comment by rahmirtrt** [comment] 2024-04-04 19:24
Thank you. It's perfect. it works.
I have tested. I will have some suggestions.

1- dgenerate 1.5x-2x slower than chainner. Can it be accelerated?

2- I am using this command.

dgenerate --sub-command image-process tmp2.jpg --output tmp2u.png -al 1 --processors "upscaler;model=models/4x_Real_SSDIR_DAT_GAN.pth"

Can a dgenerate version be made just for only upsclar models? In this way, it eliminates other unused features, speeds up and reduces its size.

3- only support (-d cuda:0) other -d cuda:1,2,3 error 'CUDA device ordinal 1 is invalid, no such device exists'

4- Could there be GPU selection support? -g gpu-id gpu device to use (default=auto) can be 0,1,2 for multi-gpu

5-Gray models do not work as in previous versions. for example this model.
004_grayDN_DFWB_s128w8_SwinIR-M_noise25.pth

**Comment by Teriks** [comment] 2024-04-05 02:57
1. I can think of a few reasons for it to be slower upfront, I will need to investigate if the tiling can be optimized any further though I am guessing chainner has a more efficient implementation of tiling.  One of the other reasons could be that dgenerate has a very slow start up time due to imports of large dependencies such as torch and friends, numpy, large machine learning librarys etc, that support its other features. As you have identified, dgenerate does many other things and it has a lot of large machine learning dependencies, upon a fresh install it will take even longer to bytecode compile all of this on the first execution.  chainner will not have such a problem with it's server client architecture, which allows those libraries to be imported once when the server launches and then used repeatedly in the same process.  This can be somewhat mitigated for batch operations by using config files, which are read in to dgenerate from STDIN and described in the readme and amongst the examples in the [example folder](https://github.com/Teriks/dgenerate/tree/master/examples), multiple operations can be preformed within the same process this way, without having to spin up a new process and incur the overhead of importing dependencies over again. I had it in mind at some point to allow dgenerate to be used as a server which takes requests as a background process, this theoretically could already be done now by talking to it over STDIN with a pipe, but I have not written any other software to facilitate talking to it this way.

2. The upscaler portion of dgenerate was implemented primarily to allow the upscaling of AI generated content produced using the various diffusion algorithms that dgenerate supports, as a post process capability on top of its primary feature set (creating AI generated images). I thought the image processing functionality internal to dgenerate would be useful as a stand alone feature, enabling upscaling and other processing of arbitrary images, so I added a way to use it in this manner on any image, I am glad this has been useful! The [image-process](https://github.com/Teriks/dgenerate/tree/master/dgenerate/image_process) sub-command and ``\image_process`` config directive uses a lot of reusable functionality I wrote for dealing with multimedia content in a generic fashion and handling alignment and resizing (images/videos) etc. [mediainput.py](https://github.com/Teriks/dgenerate/blob/master/dgenerate/mediainput.py) & [mediaoutput.py](https://github.com/Teriks/dgenerate/blob/master/dgenerate/mediaoutput.py) which is in turn very intertwined and dependent with a couple other modules within dgenerate, it could be extracted into a standalone program with quite a bit of effort, however it will still depend on some very large dependencies such as torch and numpy etc, so I am not sure if it would be worth it as the dependencies are mostly what contribute to all of the bloat.  [upscaler.py](https://github.com/Teriks/dgenerate/blob/master/dgenerate/imageprocessors/upscaler.py) is the image processor plugin which handles the upscaler functionality. It might be easier to steal this code from the upscaler plugin for standalone use than to refactor the ``image-process`` subcommand out of dgenerate, however the plugin itself does not handle any of the alignment or naive resizing functionality.

3. If am understanding correctly, you are having trouble specifying a GPU during upscaling? this can be accomplished in one of two ways demonstrated in the code box below. currently I am working on a machine with two 1080TI GPU installed and this works for me. You may need to inspect the value of your ``CUDA_VISIBLE_DEVICES`` environmental variable if this is not working on a machine which has multiple GPUs installed, [see nvidias website for details](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/).  Only if you have multiple GPUs installed in your machine that are reported as independent devices by the ``nvidia-smi`` command, can you assign jobs to a different GPU, otherwise if the device is not visible for some reason, you will get an error stating that the device ordinal does not exist. Only one GPU can ever be specified, I.E. the job cannot be distributed across multiple GPUs, the job will happen all on the specified GPU. Note that ``cuda:0`` indicates the first GPU installed in the system. A single upscaling task being distributed across multiple GPUs is not something spandrel implements, and would be difficult to implement, however I am not sure if this is what you are asking about. If your machine encounters an error with either of the following commands and you are sure that you have at least 2 independent GPUs installed in your system, could you post the dgenerate error output, the value of ``CUDA_VISIBLE_DEVICES`` in your environment, and the output of the ``nvidia-smi`` command?

```
# Run the 2nd GPU on the system

dgenerate --sub-command image-process tmp2.jpg --output tmp2u.png -al 1 --processors "upscaler;model=4x_Real_SSDIR_DAT_GAN.pth" --device cuda:1

# Or use a plugin argument

dgenerate --sub-command image-process tmp2.jpg --output tmp2u.png -al 1 --processors "upscaler;device=cuda:1;model=4x_Real_SSDIR_DAT_GAN.pth"

```

5. I see what is happening is that the model is being fed an RGB image by dgenerate when it expects an single channel grayscale image, I believe I noticed this problem with ``DDColor`` which was one of the model architectures I wanted to test that uses tiling internally.  The code for upscaling is hard coded for 3 channel images currently and I will investigate generifying it based on the instantiated upscaler models desired number of color channels.  It will require an in memory conversion to the correct number of channels IE grayscale when using those models. It may take me some time unfortunately even though it is a small fix, due to life :) but I will try to look at it as I am interested in having every model architecture working.

6. I am unsure what you mean by portable, but if you mean a single executable I am not sure it is possible with the current state of PyInstaller as a project.  It has a terrible time trying to handle the machine learning dependencies in the install folder configuration as is.  But also the executable would contain all of torch and numpy, etc. and be around as enormous as the existing install folder.  It is really hard to escape this bloat for a python ML project, the size of the dependencies required to make even just the upscaler work such as torch, numpy, possibly OpenCV are ridiculously large and incur a huge startup cost for the application. I wish it were not like this :)

**Comment by Teriks** [comment] 2024-04-05 05:34
Per .5

Model architectures expecting single channel images (IE Grayscale), including DDColor image colorization models and SwinIR gray variants etc. should be fixed by this change in the upscaler plugin:

[7f11dbb - upscaler.py](https://github.com/Teriks/dgenerate/commit/7f11dbbdfcc3f424a73cc076c0d5da62ef361d89?diff=split&w=0#diff-e999b1ebae9064a37a8c60ea1d7ed8b3e454b82ce8eaa582d184be97e144fe8a)

Incoming images which are detected to already be grayscale are simply reshaped to a single channel to conform to what the model wants as input. Image processor plugins always receive images as RGB so this reshaping / conversion is necessary.

Incoming images which are detected to be full color images are converted from color to grayscale in the process of being reshaped.

In addition, a boolean upscaler plugin option ``force-tiling`` has been added. Model architectures such as SCUNet and MixDehazeNet are no longer tiled by default unless forced by the user, as it is discouraged by the model implementation. All other model architectures where tiling is fully supported undergo external image tiling.

Architectures which tile internally such as DDColor from spandrel extra architectures no longer
undergo any external tiling and cannot be forced to undergo external tiling.  DDColor is the only
 implementation with internal tiling currently.

Version bump to 3.2.0 for technically "new features"

**Comment by Teriks** [comment] 2024-04-05 06:59
Per. 1

Attempt optimizations to tiled scaling c170807

**Comment by rahmirtrt** [comment] 2024-04-05 11:10
Can you tell me your e-mail? Let's discuss some things via e-mail.

**Comment by rahmirtrt** [comment] 2024-04-05 11:32
![nygpu](https://github.com/Teriks/dgenerate/assets/69155940/71cebf6d-28f3-4cc3-9752-df33a85df201)

3-  'CUDA_VISIBLE_DEVICES in your environment and nvidia-smi command'
I don't know how to do it or the commands.
The graphics card feature I use is in the picture.

For nccn models I use this Universal-NCNN-Upscaler.
https://github.com/TNTwise/Universal-NCNN-Upscaler
https://github.com/TNTwise/SPAN-ncnn-vulkan

Can dgenerate run ncnn files (. param . bin), what is the command?

6- I didn't mean "if you mean a single executable".
I meant the installer file (dgenerate.msi). Not a single exe. In the same way, there will be a dgenerate and _internal folder.

It can work without installing Python and others. You can make all the necessary settings in a .bat file (install.bat) for portable.

**Comment by rahmirtrt** [comment] 2024-04-05 12:13
error for cuda:1
![cuda1](https://github.com/Teriks/dgenerate/assets/69155940/4df58777-b367-41d5-b1ea-bc16a2cfe94b)

**Comment by Teriks** [comment] 2024-04-05 18:47
It appears your system has a singular GTX 1660 installed (or recognized currently by the system) in addition to intel UHD integrated graphics

The only device that supports CUDA on your system is the one GTX 1660 (device ordinal 0) which is why the other GPU is not visible to torch

Only devices listed by ``nvidia-smi`` will be compatible with acceleration with dgenerate

spandrel does not support models in NCNN format, spandrel is centered around running models with torch on Nvidia hardware / CUDA where as NCNN is made from the ground up to run on multiple types of hardware particularly mobile platforms and embedded devices

It seems there is a way convert directly from models compatible with chainner (spandrel) into NCNN for optimized use on other devices. I am not sure if there is a tool to convert NCNN models back to torch models however. It might be likely that the NCNN models you are using have a Torch format counterpart from which they were converted from, which will in turn work with dgenerate

The NCNN models might be able to have acceleration through Intel UHD graphics however this is currently not something dgenerate can do

A zip file of the PyInstaller environment itself with the generated executable would suffice for the described portable installation, it could be unzipped and run that way without the need for installer. Is this what you mean?

**Comment by Teriks** [comment] 2024-04-05 18:58
As for emailing, I wish for issue discussions to remain on the repository as opposed to email, so that the discussions can be referenced by other users who might benefit from the information

**Comment by rahmirtrt** [comment] 2024-04-05 19:46
A zip file of the PyInstaller environment itself with the generated executable would suffice for the described portable installation, it could be unzipped and run that way without the need for installer. Is this what you mean? 

yes that's what I meant.
There will only be dgenerate.exe, installset.bat and _internal folder in the zip.

**Comment by Teriks** [comment] 2024-04-06 02:14
I can create a two part zip file in the installer build prior to packaging that can be distributed this way, unzip and run from the directory.

You will need to open a command prompt in the directory of the dgenerate executable in order to run it, unless it is added to your system PATH. Or I suppose refer to it by its full path in a BAT file.

Currently all the installer does is install it and add its location to your system PATH variable for convenience so that it can be run from the command line anywhere without additional steps

**Comment by Teriks** [comment] 2024-04-06 05:34
New release should fix grayscale model issues, I have included zips of the raw executable/environment

**Comment by rahmirtrt** [comment] 2024-04-06 10:59
I have tested. 

1- I did not see any acceleration in v3.2.0 compared to other versions.
Also, when we click on dgenerate, there is a wait while loading at startup.

2- If it is not run as administrator, as in other versions, it gives this error.
image-process: error: [Errno 13] Permission denied: '.\\.lock'

3- It gives this error in the picture. for 'dn_grl_base_c3.ckpt'
![terxa](https://github.com/Teriks/dgenerate/assets/69155940/44b380ee-be34-455f-a68f-fb3282a31e97)

Some models do not work in dgenerate dn_grl_base_c3.ckpt, jpeg_grl_small_c3.ckpt.
others dn_grl_base_c3s50.ckpt... works.
all models work in chainner.

you can download it from here
https://github.com/ofsoundof/GRL-Image-Restoration/releases/

**Comment by rahmirtrt** [comment] 2024-04-06 14:34
I compared the png outputs of dgenerate and chainner. not the same. Even though the tile sizes are the same. Is it due to overlap? I tried different overlap values but could not equalize them.

**Comment by Teriks** [comment] 2024-04-06 18:14
It seems that model expects 4 channel input, IE something other than RGB.  I will need to dig through the source or find some documentation on what sort of color data it wants, I had really only considered the simple case of RGB images since that is mostly what I am working with

multithreaded processing for tiles is potentially possible but I am not sure if/when I can get around to testing out something like that, since I generally run the upscaler in batch unattended I hadn’t put an emphasis on speeding it up. From the memory overhead on the GPU on my machine it could potentially process 3 tiles simultaneously. I am unsure what this would entail because I haven’t investigated how thread safe running the models are, I am guessing they would need their own instance for each thread and to be completely isolated

I have not compared the output of chainners upscaling with dgenerate so far so I will see if I can do that

**Comment by Teriks** [comment] 2024-04-06 18:22
``\.lock`` in the output directory of dgenerate is used as a method of preventing multiple dgenerate processes from interfering with eachothers output if running simultaneously on different GPUs as a separate process.  

If this file exists or is stuck existing as owned by administrator you can safely delete it manually when dgenerate is not running

I would not run dgenerate as administrator, or with an output location where administrator privileges are required to write

**Comment by Teriks** [comment] 2024-04-06 18:44
models such as ``dn_grl_base_c1.ckpt`` from https://github.com/ofsoundof/GRL-Image-Restoration/releases/ seem to expect 2 channels even, off the top of my head I am not familiar with what sort of data it could be wanting as input :)

I will have to research

**Comment by Teriks** [comment] 2024-04-06 19:15
Chainner simply treats the 4th channel for ``dn_grl_base_c3.ckpt`` as the alpha channel of the image, as all 1s (complete opacity in the alpha channel), from what I am seeing by testing all 0.0s VS all 1.0s output in dgenerate and comparing the results, this is possibly incorrect use of the model by chainner. The result is very blurry at 1.0 opacity and not blurry at 0.0, this may be some additional image data that is meant to be consumed by the model which is not an alpha/opacity value that is not accounted for by chainner? it could be a depth value or some map that is supposed to be calculated from the input image.  It is a bit beyond the scope of dgenerate to provide this data, so I may divert to what chainner is doing and just fill it with 1.0s

**Comment by rahmirtrt** [comment] 2024-04-06 19:16
I tried these in dgenerate for chainner tile size 512 
4x_Real_SSDIR_DAT_GAN.pth;tile=512;overlap=8
4x_Real_SSDIR_DAT_GAN.pth;tile=512;overlap=16
4x_Real_SSDIR_DAT_GAN.pth;tile=512;overlap=32
These did not match exactly.
4x_Real_SSDIR_DAT_GAN.pth;tile=512;overlap=64
99% match.

I tried these in dgenerate for chainner tile size 256
4x_Real_SSDIR_DAT_GAN.pth;tile=256;overlap=1
4x_Real_SSDIR_DAT_GAN.pth;tile=256;overlap=2
4x_Real_SSDIR_DAT_GAN.pth;tile=256;overlap=8
4x_Real_SSDIR_DAT_GAN.pth;tile=256;overlap=12
4x_Real_SSDIR_DAT_GAN.pth;tile=256;overlap=16
4x_Real_SSDIR_DAT_GAN.pth;tile=256;overlap=32
4x_Real_SSDIR_DAT_GAN.pth;tile=256;overlap=64
I couldn't match it in any way.

tile size 256 chainner
![ch256](https://github.com/Teriks/dgenerate/assets/69155940/5c36806f-50b8-4016-8124-9d4e341c84c5)


256;overlap=32 dgenerate
![dg25632](https://github.com/Teriks/dgenerate/assets/69155940/d670f8be-d5d7-45fa-ac1f-a4386501515b)

**Comment by Teriks** [comment] 2024-04-06 19:33
For 2 channel models such as ``dn_grl_base_c1.ckpt`` I receive this error in chainner, I am guessing it does not attempt to down convert. I am guessing if I provide the correct image format to begin with it would work, but I am not sure what that format is.

![2channel](https://github.com/Teriks/dgenerate/assets/14919098/a1513d37-bedb-49e3-9946-dd8c28be2d4a)

I will try to investigate the output differences later tonight, it is difficult to tell with the naked eye what might be going on, it could be a combination of tiling algorithm differences, differences in image loading & saving

**Comment by rahmirtrt** [comment] 2024-04-06 19:54
Try this it works.
https://github.com/chaiNNer-org/chaiNNer-nightly/releases/download/2024-04-05/chaiNNer-windows-latest-nightly.2024-04-05.zip

Calculate and display the differences between two images
https://www.imageen.com/files/demos/run/ImageAnalysis/ImagesDiff/ImagesDiff.zip

**Comment by rahmirtrt** [comment] 2024-04-06 20:14
The 2 most important things for me (1.) are speeding up dgenerate and reducing the size (reducing the size of the _internal folder).
(2.) Can you make a special version that only runs .pth and .ckpt (models) files? 
In addition, this way it will be able to sort out many things.

**Comment by Teriks** [comment] 2024-04-07 05:13
Currently I do not have the bandwidth to refactor part of this project to isolate out just this feature into one tool and then maintain it, however I am not opposed to the code being forked or borrowed in order to do this!

Though I am interested in supporting more models if I can find the information on how they are meant to be used

After testing a smaller image 256x256, in which no tiling occurred, and testing the same image in chainner under the same condition (no tiling)

The image outputs still differed in file size and similarity between dgenerate and chainner.

This sort of leads me to believe that at least part of the difference is caused by something occurring during the loading of the image into memory and or its conversion into a Tensor before processing, that is minutely different than what is going on in the chainner code base. 

These differences would compound during tiling (especially at lower tile sizes) and processing of the image as well as during encoding while saving them to disk, especially for JPG and lossy formats.  The method of blending tiles preformed by dgenerate is also different than chainner from looking through their backend code.

I am not sure it is worth pursuing completely identical outputs unless there is serious artifacting since the outputs are very comparable visually

**Comment by rahmirtrt** [comment] 2024-04-07 06:36
https://github.com/sekiju/sr-core
you can check this out. It gives the same equal output as chainner. but it works very very slowly.

You can also check this out.
https://github.com/muslll/neosr

**Comment by rahmirtrt** [comment] 2024-04-07 18:59
Updated https://github.com/chaiNNer-org/spandrel/tree/main/libs/spandrel 
for Add support for SAFMN_BCIE.
You can add it to dgenerate.

**Comment by Teriks** [comment] 2024-04-08 05:36
Must wait for their release and the package being published to PyPi

**Comment by rahmirtrt** [comment] 2024-04-09 09:13
I follow you, you are making big changes.

**Comment by rahmirtrt** [comment] 2024-04-10 21:54
If tile=auto, what will be the overlap value?

**Comment by Teriks** [comment] 2024-04-10 23:54
It will be the default value mentioned by ‘’dgenerate —image-processor-help upscaler’’ which is 32. I neglected to check the condition of overlap potentially being more than the auto estimated optimal tile size but that should be unlikely to happen at least, with the amount of memory on most modern cards :)

**Closed** 2024-09-13 23:48 UTC
